ExoneracionProject/Pages/AdminPage/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ExoneracionProject.Data;
using ExoneracionProject.Models;

namespace ExoneracionProject.Pages.AdminPage
{
    public class CreateModel : PageModel
    {
        private readonly ExoneracionProject.Data.RecruitContext _context;

        public CreateModel(ExoneracionProject.Data.RecruitContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Admin Admin { get; set; }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Admins.Add(Admin);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

ExoneracionProject/Pages/AdminPage/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ExoneracionProject.Data;
using ExoneracionProject.Models;

namespace ExoneracionProject.Pages.AdminPage
{
    public class DeleteModel : PageModel
    {
        private readonly ExoneracionProject.Data.RecruitContext _context;

        public DeleteModel(ExoneracionProject.Data.RecruitContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Admin Admin { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Admin = await _context.Admins.FirstOrDefaultAsync(m => m.Id == id);

            if (Admin == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Admin = await _context.Admins.FindAsync(id);

            if (Admin != null)
            {
                _context.Admins.Remove(Admin);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

ExoneracionProject/Pages/AdminPage/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ExoneracionProject.Data;
using ExoneracionProject.Models;

namespace ExoneracionProject.Pages.AdminPage
{
    public class DetailsModel : PageModel
    {
        private readonly ExoneracionProject.Data.RecruitContext _context;

        public DetailsModel(ExoneracionProject.Data.RecruitContext context)
        {
            _context = context;
        }

        public Admin Admin { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Admin = await _context.Admins.FirstOrDefaultAsync(m => m.Id == id);

            if (Admin == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

ExoneracionProject/Pages/AdminPage/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExoneracionProject.Data;
using ExoneracionProject.Models;

namespace ExoneracionProject.Pages.AdminPage
{
    public class EditModel : PageModel
    {
        private readonly ExoneracionProject.Data.RecruitContext _context;

        public EditModel(ExoneracionProject.Data.RecruitContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Admin Admin { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Admin = await _context.Admins.FirstOrDefaultAsync(m => m.Id == id);

            if (Admin == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Admin).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!AdminExists(Admin.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool AdminExists(Guid id)
        {
            return _context.Admins.Any(e => e.Id == id);
        }
    }
}

ExoneracionProject/Pages/Candidato/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ExoneracionProject.Data;
using ExoneracionProject.Models;

namespace ExoneracionProject.Pages.Candidato
{
    public class CreateModel : PageModel
    {
        private readonly RecruitContext _context;
        private readonly IHtmlHelper htmlHelper;


        [BindProperty]
        public ExoneracionProject.Models.Candidato Candidato { get; set; }
        [BindProperty]
        public ExoneracionProject.Models.Competences Competences { get; set; }
        [BindProperty]
        public ExoneracionProject.Models.JobExperience JobExperience { get; set; }


        public IEnumerable<SelectListItem> Languages { get; set; }
        public IEnumerable<SelectListItem> Grades { get; set; }


        public CreateModel(RecruitContext context, IHtmlHelper htmlHelper)
        {
            _context = context;
            this.htmlHelper = htmlHelper;
        }

        public IActionResult OnGet()
        {
            Languages = htmlHelper.GetEnumSelectList<Language>();
            Grades = htmlHelper.GetEnumSelectList<Grades>();
            //ViewData["JobId"] = new SelectList(_context.Jobs, "Id", "Id");
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                Languages = htmlHelper.GetEnumSelectList<Language>();
                Grades = htmlHelper.GetEnumSelectList<Grades>();
                return Page();
            }

            Candidato.Id = Guid.NewGuid();
            JobExperience.CandidatoId = Candidato.Id;
            Competences.CandidatoId = Candidato.Id;


            _context.Candidatos.Add(Candidato);
            _context.Competences.Add(Competences);
            _context.JobExperiences.Add(JobExperience);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

ExoneracionProject/Pages/Candidato/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ExoneracionProject.Data;
using ExoneracionProject.Models;

namespace ExoneracionProject.Pages.Candidato
{
    public class DeleteModel : PageModel
    {
        private readonly ExoneracionProject.Data.RecruitContext _context;

        public DeleteModel(ExoneracionProject.Data.RecruitContext context)
        {
            _context = context;
        }

        [BindProperty]
        public ExoneracionProject.Models.Candidato Candidato { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Candidato = await _context.Candidatos
                .Include(c => c.Job).FirstOrDefaultAsync(m => m.Id == id);

            if (Candidato == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Candidato = await _context.Candidatos.FindAsync(id);

            if (Candidato != null)
            {
                _context.Candidatos.Remove(Candidato);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

ExoneracionProject/Pages/Candidato/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ExoneracionProject.Data;
using ExoneracionProject.Models;

namespace ExoneracionProject.Pages.Candidato
{
    public class DetailsModel : PageModel
    {
        private readonly ExoneracionProject.Data.RecruitContext _context;

        public DetailsModel(ExoneracionProject.Data.RecruitContext context)
        {
            _context = context;
        }


        public ExoneracionProject.Models.Candidato Candidato { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Candidato = await _context.Candidatos
                .Include(c => c.Job).FirstOrDefaultAsync(m => m.Id == id);

            if (Candidato == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

ExoneracionProject/Pages/Candidato/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ExoneracionProject.Data;
using ExoneracionProject.Models;

namespace ExoneracionProject.Pages.Candidato
{
    public class EditModel : PageModel
    {
        private readonly ExoneracionProject.Data.RecruitContext _context;
        private readonly IHtmlHelper htmlHelper;

        public EditModel(ExoneracionProject.Data.RecruitContext context, IHtmlHelper htmlHelper)
        {
            _context = context;
            this.htmlHelper = htmlHelper;
        }

        public IEnumerable<SelectListItem> Languages { get; set; }
        public IEnumerable<SelectListItem> Grades { get; set; }
        [BindProperty]
        public ExoneracionProject.Models.Candidato Candidato { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Languages = htmlHelper.GetEnumSelectList<Language>();
            Grades = htmlHelper.GetEnumSelectList<Grades>();

            Candidato = await _context.Candidatos
                .Include(c => c.Job)
                .Include(c => c.Competences)
                .Include(c => c.JobExperiences)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (Candidato == null)
            {
                return NotFound();
            }
          // ViewData["JobId"] = new SelectList(_context.Jobs, "Id", "Id");
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Candidato).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!CandidatoExists(Candidato.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool CandidatoExists(Guid id)
        {
            return _context.Candidatos.Any(e => e.Id == id);
        }
    }
}

ExoneracionProject/Pages/Job/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ExoneracionProject.Data;
using ExoneracionProject.Models;

namespace ExoneracionProject.Pages.Job
{
    public class CreateModel : PageModel
    {
        private readonly ExoneracionProject.Data.RecruitContext _context;

        public CreateModel(ExoneracionProject.Data.RecruitContext context)
        {
            _context = context;
            Job = new Models.Job();
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public ExoneracionProject.Models.Job Job { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Jobs.Add(Job);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

ExoneracionProject/Pages/Job/Details.cshtml.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Identity;
using ExoneracionProject.Models;
using ExoneracionProject.Data;

namespace ExoneracionProject.Pages.Job
{
    public class DetailsModel : PageModel
    {
        private readonly ExoneracionProject.Data.RecruitContext _context;
        private readonly Microsoft.AspNetCore.Identity.UserManager<IdentityUser> userManager;

        public DetailsModel(ExoneracionProject.Data.RecruitContext context, 
            Microsoft.AspNetCore.Identity.UserManager<IdentityUser> userManager)
        {
            _context = context;
            this.userManager = userManager;
            NewCandidato = new Models.Candidato();
            NewJob = new Models.Job();
        }
        public ExoneracionProject.Models.Job Job { get; set; }

        public ExoneracionProject.Models.Candidato Candidato { get; set; }
        [BindProperty]
        public ExoneracionProject.Models.Candidato NewCandidato { get; set; }
        [BindProperty]
        public ExoneracionProject.Models.Job NewJob { get; set; }

        public async Task<IActionResult> OnGetAsync(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            Job = await _context.Jobs
                .Include(j => j.Candidatos)
                    .ThenInclude(c=>c.Competences)
                .Include(j => j.Candidatos)
                    .ThenInclude(c => c.JobExperiences)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (Job == null)
            {
                return NotFound();
            }
            return Page();
        }
        public async Task<IActionResult> OnPostAsync(Guid jobId, string salary)
        {
            var user = await userManager.GetUserAsync(HttpContext.User);

            if (!ModelState.IsValid)
            {
                return Page();
            }

            Candidato = await _context.Candidatos.FirstOrDefaultAsync(c => c.Id == Guid.Parse(user.Id));

            Candidato.Salary = salary;
            Candidato.JobId = jobId;
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }

        public async Task<IActionResult> OnPostHireAsync()
        {
            Candidato = await _context.Candidatos.FirstOrDefaultAsync(c => c.Id == NewCandidato.Id);
            Job = await _context.Jobs.FirstOrDefaultAsync(j => j.Id == NewJob.Id);

            var employee = new Admin()
            {
                Id = Candidato.Id,
                Name = Candidato.Name,
                Nationalidentifier = Candidato.NationalIdentifier,
                StartDate = DateTime.Today.Date,
                JobTittle = Job.JobName,
                Salary = int.Parse(NewCandidato.Salary),
                Status = true,
            };

            _context.Admins.Add(employee);
            await _context.SaveChangesAsync();
            _context.Candidatos.Remove(Candidato);
            await _context.SaveChangesAsync();
            _context.Jobs.Remove(Job);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

ExoneracionProject/Pages/Job/Create.cshtml
@page
@model ExoneracionProject.Pages.Job.CreateModel

@{
    ViewData["Title"] = "Create";
}

<script src="~/js/amount_format.js"></script>

<h1>Create</h1>

<h4>Job</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row col-12">
                <div class="form-group col-4">
                    <label asp-for="Job.JobName" class="control-label"> Job Title</label>
                    <input asp-for="Job.JobName" class="form-control" />
                    <span asp-validation-for="Job.JobName" class="text-danger"></span>
                </div>
                <div class="form-group col-4">
                    <label asp-for="Job.MinSalary" class="control-label"></label>
                    <input asp-for="Job.MinSalary" id="min" class="form-control" />
                    <span asp-validation-for="Job.MinSalary" class="text-danger"></span>
                </div>
                -
                <div class="form-group col-4">
                    <label asp-for="Job.MaxSalary" class="control-label"></label>
                    <input data-type="currency" id="max" type="text" asp-for="Job.MaxSalary" class="form-control" />
                    <span asp-validation-for="Job.MaxSalary" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Job.Status" /> @Html.DisplayNameFor(model => model.Job.Status)
                </label>
            </div>
            <div class="form-group">
                <input type="submit" onclick="CreateJob()" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

<script>
    function CreateJob(minSal, maxSal) {
        var min = $('#min').val();
        var max = $('#max').val();

        if (parseInt(min) > parseInt(max)) {
            alert("Oferta de salario invalido");
            event.preventDefault();
            location.reload();
        }
    }
</script>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExoneracionProject/Pages/Job/Delete.cshtml
@page
@model ExoneracionProject.Pages.Job.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Job</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Job.JobName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Job.JobName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Job.MinSalary)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Job.MinSalary)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Job.MaxSalary)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Job.MaxSalary)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Job.Status)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Job.Status)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Job.Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

ExoneracionProject/Pages/Job/Details.cshtml
@page
@model ExoneracionProject.Pages.Job.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

@if (User.IsInRole("Admin"))
{
    <div>
        <h4>Job</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Job.JobName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Job.JobName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Job.MinSalary)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Job.MinSalary)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Job.MaxSalary)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Job.MaxSalary)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Job.Status)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Job.Status)
            </dd>
        </dl>
        <hr />
        <h4>Recruits</h4>
        @foreach (var item in Model.Job.Candidatos)
        {

            <dl class="row">
                <dt class="col-sm-2">
                    Name:
                </dt>
                <dd class="col-sm-2">
                    @item.Name
                </dd>
                <dt class="col-sm-2">
                    Age:
                </dt>
                <dd>
                    @item.Age
                </dd>
                <dt class="col-sm-2">
                    Salary:
                </dt>
                <dd class="col-sm-2">
                    @item.Salary
                </dd>
                <dt class="col-sm-2">
                    Grades:
                </dt>
                <dd class="col-sm-2">
                    @item.Grades
                </dd>
                <div class="row col-12">
                    <dt class="col-sm-2">
                        Competences:
                    </dt>
                    <dd class="col-sm-10">
                        @foreach (var Compe in item.Competences)
                        {
                            @Compe.Description<br />
                        }
                    </dd>
                </div>
                <div class="row col-12">
                    <dt class="col-sm-2">
                        Previous Jobs:
                    </dt>
                    <dd class="col-sm-10">
                        @foreach (var pJ in item.JobExperiences)
                        {
                            <hr />
                            <br />
                            @pJ.CompanyName<br />
                            @pJ.JobTittle<br />
                            @pJ.Salary<br />
                            @pJ.From
                            @pJ.To
                        }
                    </dd>
                </div>

            </dl>
            <button class="btn btn-primary" onclick="HireEmployee('@item.Id', '@Model.Job.Id')" data-toggle="modal" data-target="#employee-hire">Hire</button>
        }
    </div>
}
else
{
    <div class="row">
        <div class="col-md-12">
            <form method="post">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" value="@Model.Job.Id" name="jobId"/>
                <div class="row">
                    <div class="form-group col-4">
                        <label asp-for="Candidato.Salary" class="control-label"></label>
                        <input name="salary" id="salarySug" class="form-control" />
                        <span asp-validation-for="Candidato.Salary" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" value="Apply" onclick="Apply('@Model.Job.MinSalary', '@Model.Job.MaxSalary')" class="btn btn-primary" />
                </div>
            </form>
            <hr />
            <div>
                <h4>Job</h4>
                <hr />
                <dl class="row">
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Job.JobName)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Job.JobName)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Job.MinSalary)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Job.MinSalary)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Job.MaxSalary)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Job.MaxSalary)
                    </dd>
                    <dt class="col-sm-2">
                        @Html.DisplayNameFor(model => model.Job.Status)
                    </dt>
                    <dd class="col-sm-10">
                        @Html.DisplayFor(model => model.Job.Status)
                    </dd>
                </dl>
            </div>
        </div>
    </div>
}

<div class="modal fade" id="employee-hire">
    <div class="modal-dialog">
        <form class="modal-content" enctype="multipart/form-data" method="post" asp-page="/Job/Details">
            <div class="modal-header">
                <h5 class="modal-title">
                    Hire
                </h5>
            </div>
            <div class="modal-body">
                <div class="form-group row jumbotron mx-0" style="height: 35px; padding: 0px 10px;">
                    <label class="col-form-label col-sm-12 text-sm-lef">Job: @Model.Job.JobName</label>
                    <input type="text" id="RecruitId" asp-for="@Model.NewCandidato.Id" hidden />
                    <input type="text" id="JobId" asp-for="@Model.NewJob.Id" hidden />
                </div>
                <div class="form-group">
                    <label for="message-text" class="col-form-label">Salary:</label>
                    <input class="form-control" id="salaryInput" asp-for="@Model.NewCandidato.Salary"/>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-round btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" onclick="HireVerification('@Model.Job.MinSalary', '@Model.Job.MaxSalary')" class="btn btn-round btn-success" asp-page-handler="Hire">Hire a Employee</button>
            </div>
        </form>
    </div>
</div>


<script>
    function HireEmployee(Id, JobId) {
        $('#RecruitId').val(Id);
        $('#JobId').val(JobId);
    };

    function HireVerification(minSal, maxSal) {
        var min = minSal;
        var max = maxSal;

        var salary = $("#salaryInput").val();

        if (parseInt(min) > parseInt(salary) || parseInt(salary) > parseInt(max)) {
            alert("Salario invalido");
            event.preventDefault();
            location.reload();
        }
    }

    function Apply(minSal, maxSal) {
        var min = minSal;
        var max = maxSal;

        var salary = $("#salarySug").val();

        if (parseInt(min) > parseInt(salary) || parseInt(salary) > parseInt(max)) {
            alert("Sugerencia de salario invalido");
            event.preventDefault();
            location.reload();
        }
    }
</script>

<div>
    <a asp-page="./Edit" asp-route-id="@Model.Job.Id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

ExoneracionProject/Pages/Job/Edit.cshtml
@page
@model ExoneracionProject.Pages.Job.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Job</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Job.Id" />
            <div class="form-group">
                <label asp-for="Job.JobName" class="control-label"></label>
                <input asp-for="Job.JobName" class="form-control" />
                <span asp-validation-for="Job.JobName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Job.MinSalary" class="control-label"></label>
                <input asp-for="Job.MinSalary" id="min" class="form-control" />
                <span asp-validation-for="Job.MinSalary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Job.MaxSalary" class="control-label"></label>
                <input asp-for="Job.MaxSalary" id="max" class="form-control" />
                <span asp-validation-for="Job.MaxSalary" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="Job.Status" /> @Html.DisplayNameFor(model => model.Job.Status)
                </label>
            </div>
            <div class="form-group">
                <input type="submit"  onclick="EditJob()" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

<script>
    function EditJob(minSal, maxSal) {
        var min = $('#min').val();
        var max = $('#max').val();

        if (parseInt(min) > parseInt(max)) {
            alert("Oferta de salario invalido");
            event.preventDefault();
            location.reload();
        }
    }
</script>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}