ExoneracionProject/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace ExoneracionProject.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

ExoneracionProject/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace ExoneracionProject.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

ExoneracionProject/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace ExoneracionProject.Pages
{
    [Authorize]
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

ExoneracionProject/Pages/Report.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ExoneracionProject.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace ExoneracionProject.Pages
{
    public class ReportModel : PageModel
    {
        private readonly Data.RecruitContext _context;
        private readonly UserManager<IdentityUser> userManager;

        public ReportModel(Data.RecruitContext context,
                            UserManager<IdentityUser> userManager)
        {
            _context = context;
            this.userManager = userManager;
        }


        [BindProperty]
        public DateTime? StartDateFilter { get; set; }

        public List<Admin> Admins { get; set; }

        public void OnGet()
        {
            Admins = _context.Admins.ToList();
        }
        public async Task<IActionResult> OnPostDateFilter()
        {
            Admins = await _context.Admins.Where(a => a.StartDate >= StartDateFilter).ToListAsync();
            return Page();
        }

    }
}

ExoneracionProject/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ExoneracionProject/Pages/Report.cshtml
@page

@model ExoneracionProject.Pages.ReportModel
@{
}

<form class="modal-content" enctype="multipart/form-data" method="post" asp-page="/Report/Details">
    <input asp-for="@Model.StartDateFilter" />
    <div class="form-group">
        <button type="button" class="btn btn-round btn-secondary" data-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-round btn-success" asp-page-handler="DateFilter" asp-route-startDate="@Model.StartDateFilter">Search by Start Date</button>
    </div>
</form>

<hr />
@if (Model.StartDateFilter.HasValue)
{
    <h1>Empleados que ingresaron a partir de: @Model.StartDateFilter.Value.ToShortDateString() </h1>
}
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Admins[0].Nationalidentifier)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Admins[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Admins[0].StartDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Admins[0].Department)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Admins[0].JobTittle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Admins[0].Salary)
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Admins)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nationalidentifier)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.StartDate)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Department)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.JobTittle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Salary)
                </td>
            </tr>
        }
    </tbody>
</table>